export { default as Homepage } from './homepage/Homepage'
export { default as Register } from './register/Rigester'
export { default as SignIn } from './signIn/SignIn'
export { default as Dashbord } from './dashbord/Dashbord'
export { default as AddTask } from './addtask/AddTask'